from app.db.tables import role_permissions
from app.models.asset import Asset
from app.models.asset_history import AssetHistory
from app.models.asset_import_batch import AssetImportBatch
from app.models.asset_import_row import AssetImportRow
from app.models.asset_assignment import AssetAssignment
from app.models.asset_type import AssetType
from app.models.ai_suggestion import AiSuggestion
from app.models.approval_request import ApprovalRequest
from app.models.audit_log import AuditLog
from app.models.automation_action_log import AutomationActionLog
from app.models.automation_rule import AutomationRule
from app.models.automation_run import AutomationRun
from app.models.email_message_log import EmailMessageLog
from app.models.external_system import ExternalSystem
from app.models.import_job import ImportJob
from app.models.integration_credential import IntegrationCredential
from app.models.integration_event_log import IntegrationEventLog
from app.models.integration_mapping import IntegrationMapping
from app.models.job_run import JobRun
from app.models.job_queue_outbox import JobQueueOutbox
from app.models.job_lifecycle_event import JobLifecycleEvent
from app.models.job_event_consumer_delivery import JobEventConsumerDelivery
from app.models.job_event_consumer_offset import JobEventConsumerOffset
from app.models.knowledge_article import KnowledgeArticle
from app.models.knowledge_article_feedback import KnowledgeArticleFeedback
from app.models.knowledge_category import KnowledgeCategory
from app.models.knowledge_usage_log import KnowledgeUsageLog
from app.models.notification import Notification
from app.models.notification_preference import NotificationPreference
from app.models.notification_template import NotificationTemplate
from app.models.system_setting import SystemSetting
from app.models.ticket_category import TicketCategory
from app.models.ticket_comment import TicketComment
from app.models.ticket_history import TicketHistory
from app.models.ticket_priority import TicketPriority
from app.models.ticket_status import TicketStatus
from app.models.user_role import UserRole
from app.models.permission import Permission
from app.models.report_snapshot import ReportSnapshot
from app.models.role import Role
from app.models.runbook import Runbook
from app.models.runbook_execution import RunbookExecution
from app.models.saved_report import SavedReport
from app.models.sla import SlaPolicy
from app.models.sla_event import SlaEvent
from app.models.tenant import Tenant
from app.models.ticket import Ticket
from app.models.ticket_knowledge_link import TicketKnowledgeLink
from app.models.user import User
from app.models.webhook_endpoint import WebhookEndpoint
