import { Link } from 'react-router-dom'
import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { fetchEmailLog, sendTestEmail } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import AppShell from '../components/AppShell'

function formatDateTime(value: string | null) {
  if (!value) return '—'
  return new Intl.DateTimeFormat('ru-RU', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))
}

export default function EmailLogPage() {
  const { session } = useAuth()
  const queryClient = useQueryClient()
  const [statusFilter, setStatusFilter] = useState('ALL')
  const [search, setSearch] = useState('')

  const emailLogQuery = useQuery({
    queryKey: ['email-log', session?.access_token],
    queryFn: () => fetchEmailLog(session?.access_token ?? ''),
    enabled: Boolean(session?.access_token),
  })

  const testEmailMutation = useMutation({
    mutationFn: async () => {
      if (!session?.access_token) throw new Error('No session')
      return sendTestEmail(session.access_token, {
        to_email: 'demo-notify@sbs.local',
        subject: 'NOTIFICATION-EMAIL-001 test',
        body: 'This message is generated by MockEmailProvider and stored in log only.',
      })
    },
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ['email-log'] })
    },
  })

  const logs = emailLogQuery.data ?? []
  const filteredLogs = useMemo(
    () => logs.filter((item) => (statusFilter === 'ALL' || item.status === statusFilter) && (!search.trim() || item.to_email.toLowerCase().includes(search.trim().toLowerCase()) || item.subject.toLowerCase().includes(search.trim().toLowerCase()))),
    [logs, statusFilter, search],
  )
  const queued = logs.filter((item) => item.status === 'PENDING').length
  const sent = logs.filter((item) => item.status === 'SENT').length
  const failed = logs.filter((item) => item.status === 'FAILED').length

  return (
    <AppShell title="Email Log" subtitle="Журнал mock-email сообщений и будущих email-интеграций.">
      <section className="section-card">
        <div>
          <p className="eyebrow">EMAIL PROVIDER FOUNDATION</p>
          <h2>Журнал mock-email</h2>
          <p>Все операции email сохраняются локально в EmailMessageLog и не отправляются наружу.</p>
        </div>
        <div className="status-column">
          <button
            type="button"
            className="ghost-button"
            onClick={() => {
              const confirmed = window.confirm('Сгенерировать тестовое письмо в mock-email журнале?')
              if (!confirmed) return
              testEmailMutation.mutate()
            }}
            disabled={testEmailMutation.isPending}
          >
            {testEmailMutation.isPending ? 'Создание…' : 'Тестовый mock-email'}
          </button>
        </div>
      </section>

      <nav className="module-subnav" aria-label="Notifications navigation">
        <Link to="/notifications" className="module-subnav-tab">Уведомления</Link>
        <Link to="/notifications/email-log" className="module-subnav-tab active">Email Log</Link>
      </nav>

      {testEmailMutation.isError ? <p className="error-message">Не удалось создать тестовый mock-email.</p> : null}

      <section className="module-overview-grid">
        <article className="metric-card">
          <span>Email в очереди</span>
          <strong>{queued}</strong>
          <p>Статус PENDING</p>
        </article>
        <article className="metric-card">
          <span>Отправлено mock-email</span>
          <strong>{sent}</strong>
          <p>Статус SENT</p>
        </article>
        <article className="metric-card">
          <span>Ошибки отправки</span>
          <strong>{failed}</strong>
          <p>Статус FAILED</p>
        </article>
      </section>

      <section className="foundation-card table-toolbar">
        <div className="table-filters">
          <label className="inline-field">
            <span>Поиск</span>
            <input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Тема или получатель" />
          </label>
          <label className="inline-field">
            <span>Статус</span>
            <select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}>
              <option value="ALL">Все</option>
              <option value="PENDING">Ожидает</option>
              <option value="SENT">Отправлено</option>
              <option value="FAILED">Ошибка</option>
            </select>
          </label>
        </div>
      </section>

      <section className="section-card notification-list-shell">
        {emailLogQuery.isPending ? (
          <p className="loading-state">Загрузка данных...</p>
        ) : emailLogQuery.isError ? (
          <div className="error-state">
            Не удалось загрузить email log.
            <div className="analytics-actions">
              <button type="button" className="ghost-button" onClick={() => emailLogQuery.refetch()}>Повторить</button>
            </div>
          </div>
        ) : filteredLogs.length === 0 ? (
          <p className="empty-state">Данных пока нет. Создайте тестовый mock-email или измените фильтры.</p>
        ) : (
          <div className="ticket-table-wrap">
            <table className="ticket-table">
              <thead>
                <tr>
                  <th>Получатель</th>
                  <th>Тема</th>
                  <th>Статус</th>
                  <th>Связанная заявка</th>
                  <th>Создано</th>
                  <th>Отправлено</th>
                  <th>Ошибка</th>
                </tr>
              </thead>
              <tbody>
                {filteredLogs.map((item) => (
                  <tr key={item.id}>
                    <td>{item.to_email}</td>
                    <td>{item.subject}</td>
                    <td>{item.status}</td>
                    <td>{item.related_ticket_id ? item.related_ticket_id.slice(0, 8) : '—'}</td>
                    <td>{formatDateTime(item.created_at)}</td>
                    <td>{formatDateTime(item.sent_at)}</td>
                    <td>{item.error_message ?? '—'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </AppShell>
  )
}
