import { Link } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { fetchEmailLog, sendTestEmail } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import AppShell from '../components/AppShell'

function formatDateTime(value: string | null) {
  if (!value) return '—'
  return new Intl.DateTimeFormat('ru-RU', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))
}

export default function EmailLogPage() {
  const { session } = useAuth()
  const queryClient = useQueryClient()

  const emailLogQuery = useQuery({
    queryKey: ['email-log', session?.access_token],
    queryFn: () => fetchEmailLog(session?.access_token ?? ''),
    enabled: Boolean(session?.access_token),
  })

  const testEmailMutation = useMutation({
    mutationFn: async () => {
      if (!session?.access_token) throw new Error('No session')
      return sendTestEmail(session.access_token, {
        to_email: 'demo-notify@sbs.local',
        subject: 'NOTIFICATION-EMAIL-001 test',
        body: 'This message is generated by MockEmailProvider and stored in log only.',
      })
    },
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ['email-log'] })
    },
  })

  const logs = emailLogQuery.data ?? []
  const queued = logs.filter((item) => item.status === 'PENDING').length
  const sent = logs.filter((item) => item.status === 'SENT').length
  const failed = logs.filter((item) => item.status === 'FAILED').length

  return (
    <AppShell title="Email log" subtitle="MockEmailProvider сохраняет каждую отправку в журнал без подключения SMTP/Zimbra.">
      <section className="foundation-card notifications-toolbar">
        <div>
          <p className="eyebrow">EMAIL PROVIDER FOUNDATION</p>
          <h2>Журнал mock-email</h2>
          <p>Все операции email сохраняются локально в EmailMessageLog и не отправляются наружу.</p>
        </div>
        <div className="status-column">
          <div className="notification-tabs">
            <Link to="/notifications">Уведомления</Link>
            <Link to="/notifications/email-log" className="active">Email log</Link>
          </div>
          <button type="button" className="ghost-button" onClick={() => testEmailMutation.mutate()} disabled={testEmailMutation.isPending}>
            {testEmailMutation.isPending ? 'Создание…' : 'Тестовый mock-email'}
          </button>
        </div>
      </section>

      <section className="metric-grid dashboard-metrics">
        <article className="metric-card">
          <span>Email в очереди</span>
          <strong>{queued}</strong>
          <p>Статус PENDING</p>
        </article>
        <article className="metric-card">
          <span>Отправлено mock-email</span>
          <strong>{sent}</strong>
          <p>Статус SENT</p>
        </article>
        <article className="metric-card">
          <span>Ошибки отправки</span>
          <strong>{failed}</strong>
          <p>Статус FAILED</p>
        </article>
      </section>

      <section className="foundation-card notification-list-shell">
        {emailLogQuery.isPending ? (
          <p className="muted">Загрузка email log…</p>
        ) : emailLogQuery.isError ? (
          <p className="error-message">Не удалось загрузить email log.</p>
        ) : logs.length === 0 ? (
          <p className="muted">Лог пуст. Создайте тестовый mock-email.</p>
        ) : (
          <div className="ticket-table-wrap">
            <table className="ticket-table">
              <thead>
                <tr>
                  <th>Получатель</th>
                  <th>Тема</th>
                  <th>Статус</th>
                  <th>Связанная заявка</th>
                  <th>Создано</th>
                  <th>Отправлено</th>
                  <th>Ошибка</th>
                </tr>
              </thead>
              <tbody>
                {logs.map((item) => (
                  <tr key={item.id}>
                    <td>{item.to_email}</td>
                    <td>{item.subject}</td>
                    <td>{item.status}</td>
                    <td>{item.related_ticket_id ? item.related_ticket_id.slice(0, 8) : '—'}</td>
                    <td>{formatDateTime(item.created_at)}</td>
                    <td>{formatDateTime(item.sent_at)}</td>
                    <td>{item.error_message ?? '—'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </AppShell>
  )
}
